/// Flutter icons IconosApp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconosApp
///      fonts:
///       - asset: fonts/IconosApp.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class IconosApp {
  IconosApp._();

  static const _kFontFam = 'IconosApp';
  static const String? _kFontPkg = null;

  static const IconData toys = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swimming = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chess = IconData(0xf439, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData table_tennis = IconData(0xf45d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
